# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ruhtra/trav/structurededonne

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ruhtra/trav/structurededonne

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruhtra/trav/structurededonne/CMakeFiles /home/ruhtra/trav/structurededonne/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruhtra/trav/structurededonne/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ./bin/TP1/TP1_fact

# Build rule for target.
./bin/TP1/TP1_fact: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/TP1/TP1_fact
.PHONY : ./bin/TP1/TP1_fact

# fast build rule for target.
./bin/TP1/TP1_fact/fast:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_fact.dir/build.make CMakeFiles/./bin/TP1/TP1_fact.dir/build
.PHONY : ./bin/TP1/TP1_fact/fast

#=============================================================================
# Target rules for targets named ./bin/TP1/TP1_list_test

# Build rule for target.
./bin/TP1/TP1_list_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/TP1/TP1_list_test
.PHONY : ./bin/TP1/TP1_list_test

# fast build rule for target.
./bin/TP1/TP1_list_test/fast:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/build
.PHONY : ./bin/TP1/TP1_list_test/fast

src/TP1/factoriel.o: src/TP1/factoriel.c.o

.PHONY : src/TP1/factoriel.o

# target to build an object file
src/TP1/factoriel.c.o:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_fact.dir/build.make CMakeFiles/./bin/TP1/TP1_fact.dir/src/TP1/factoriel.c.o
.PHONY : src/TP1/factoriel.c.o

src/TP1/factoriel.i: src/TP1/factoriel.c.i

.PHONY : src/TP1/factoriel.i

# target to preprocess a source file
src/TP1/factoriel.c.i:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_fact.dir/build.make CMakeFiles/./bin/TP1/TP1_fact.dir/src/TP1/factoriel.c.i
.PHONY : src/TP1/factoriel.c.i

src/TP1/factoriel.s: src/TP1/factoriel.c.s

.PHONY : src/TP1/factoriel.s

# target to generate assembly for a file
src/TP1/factoriel.c.s:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_fact.dir/build.make CMakeFiles/./bin/TP1/TP1_fact.dir/src/TP1/factoriel.c.s
.PHONY : src/TP1/factoriel.c.s

src/TP1/list/data.o: src/TP1/list/data.c.o

.PHONY : src/TP1/list/data.o

# target to build an object file
src/TP1/list/data.c.o:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/data.c.o
.PHONY : src/TP1/list/data.c.o

src/TP1/list/data.i: src/TP1/list/data.c.i

.PHONY : src/TP1/list/data.i

# target to preprocess a source file
src/TP1/list/data.c.i:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/data.c.i
.PHONY : src/TP1/list/data.c.i

src/TP1/list/data.s: src/TP1/list/data.c.s

.PHONY : src/TP1/list/data.s

# target to generate assembly for a file
src/TP1/list/data.c.s:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/data.c.s
.PHONY : src/TP1/list/data.c.s

src/TP1/list/list.o: src/TP1/list/list.c.o

.PHONY : src/TP1/list/list.o

# target to build an object file
src/TP1/list/list.c.o:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/list.c.o
.PHONY : src/TP1/list/list.c.o

src/TP1/list/list.i: src/TP1/list/list.c.i

.PHONY : src/TP1/list/list.i

# target to preprocess a source file
src/TP1/list/list.c.i:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/list.c.i
.PHONY : src/TP1/list/list.c.i

src/TP1/list/list.s: src/TP1/list/list.c.s

.PHONY : src/TP1/list/list.s

# target to generate assembly for a file
src/TP1/list/list.c.s:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/list.c.s
.PHONY : src/TP1/list/list.c.s

src/TP1/list/maillon.o: src/TP1/list/maillon.c.o

.PHONY : src/TP1/list/maillon.o

# target to build an object file
src/TP1/list/maillon.c.o:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/maillon.c.o
.PHONY : src/TP1/list/maillon.c.o

src/TP1/list/maillon.i: src/TP1/list/maillon.c.i

.PHONY : src/TP1/list/maillon.i

# target to preprocess a source file
src/TP1/list/maillon.c.i:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/maillon.c.i
.PHONY : src/TP1/list/maillon.c.i

src/TP1/list/maillon.s: src/TP1/list/maillon.c.s

.PHONY : src/TP1/list/maillon.s

# target to generate assembly for a file
src/TP1/list/maillon.c.s:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/maillon.c.s
.PHONY : src/TP1/list/maillon.c.s

src/TP1/list/test.o: src/TP1/list/test.c.o

.PHONY : src/TP1/list/test.o

# target to build an object file
src/TP1/list/test.c.o:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/test.c.o
.PHONY : src/TP1/list/test.c.o

src/TP1/list/test.i: src/TP1/list/test.c.i

.PHONY : src/TP1/list/test.i

# target to preprocess a source file
src/TP1/list/test.c.i:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/test.c.i
.PHONY : src/TP1/list/test.c.i

src/TP1/list/test.s: src/TP1/list/test.c.s

.PHONY : src/TP1/list/test.s

# target to generate assembly for a file
src/TP1/list/test.c.s:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/test.c.s
.PHONY : src/TP1/list/test.c.s

src/TP1/list/test/test_list.o: src/TP1/list/test/test_list.c.o

.PHONY : src/TP1/list/test/test_list.o

# target to build an object file
src/TP1/list/test/test_list.c.o:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/test/test_list.c.o
.PHONY : src/TP1/list/test/test_list.c.o

src/TP1/list/test/test_list.i: src/TP1/list/test/test_list.c.i

.PHONY : src/TP1/list/test/test_list.i

# target to preprocess a source file
src/TP1/list/test/test_list.c.i:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/test/test_list.c.i
.PHONY : src/TP1/list/test/test_list.c.i

src/TP1/list/test/test_list.s: src/TP1/list/test/test_list.c.s

.PHONY : src/TP1/list/test/test_list.s

# target to generate assembly for a file
src/TP1/list/test/test_list.c.s:
	$(MAKE) -f CMakeFiles/./bin/TP1/TP1_list_test.dir/build.make CMakeFiles/./bin/TP1/TP1_list_test.dir/src/TP1/list/test/test_list.c.s
.PHONY : src/TP1/list/test/test_list.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ./bin/TP1/TP1_fact"
	@echo "... test"
	@echo "... ./bin/TP1/TP1_list_test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/TP1/factoriel.o"
	@echo "... src/TP1/factoriel.i"
	@echo "... src/TP1/factoriel.s"
	@echo "... src/TP1/list/data.o"
	@echo "... src/TP1/list/data.i"
	@echo "... src/TP1/list/data.s"
	@echo "... src/TP1/list/list.o"
	@echo "... src/TP1/list/list.i"
	@echo "... src/TP1/list/list.s"
	@echo "... src/TP1/list/maillon.o"
	@echo "... src/TP1/list/maillon.i"
	@echo "... src/TP1/list/maillon.s"
	@echo "... src/TP1/list/test.o"
	@echo "... src/TP1/list/test.i"
	@echo "... src/TP1/list/test.s"
	@echo "... src/TP1/list/test/test_list.o"
	@echo "... src/TP1/list/test/test_list.i"
	@echo "... src/TP1/list/test/test_list.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

